// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektniZadatak;

#nullable disable

namespace ProjektniZadatak.Migrations
{
    [DbContext(typeof(DrustvenaMrezaDbContext))]
    partial class DrustvenaMrezaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektniZadatak.Controllers.Model.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("objavaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("objavaId");

                    b.ToTable("Komentari");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Lajk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObjavaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjavaId");

                    b.ToTable("Lajkovi");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Objava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Objave");
                });

            modelBuilder.Entity("ProjektniZadatak.Controllers.Model.Korisnik", b =>
                {
                    b.HasOne("ProjektniZadatak.Controllers.Model.Korisnik", null)
                        .WithMany("PraceniKorisnici")
                        .HasForeignKey("KorisnikId");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Komentar", b =>
                {
                    b.HasOne("ProjektniZadatak.Models.Objava", "PovezanaObjava")
                        .WithMany("SviKomentari")
                        .HasForeignKey("objavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PovezanaObjava");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Lajk", b =>
                {
                    b.HasOne("ProjektniZadatak.Models.Objava", "PovezanaObjava")
                        .WithMany("SviLajkovi")
                        .HasForeignKey("ObjavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PovezanaObjava");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Objava", b =>
                {
                    b.HasOne("ProjektniZadatak.Controllers.Model.Korisnik", "Autor")
                        .WithMany("Objave")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("ProjektniZadatak.Controllers.Model.Korisnik", b =>
                {
                    b.Navigation("Objave");

                    b.Navigation("PraceniKorisnici");
                });

            modelBuilder.Entity("ProjektniZadatak.Models.Objava", b =>
                {
                    b.Navigation("SviKomentari");

                    b.Navigation("SviLajkovi");
                });
#pragma warning restore 612, 618
        }
    }
}
